version: 2.1
jobs:
  build:
    docker:
      - image: regviz/node-xcb

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules
          key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          name: Cache node_modules
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: screenshots
          command: yarn screenshot

      - run:
          name: regression
          command: yarn regression --quiet